# Generated by Django 4.1.7 on 2023-04-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_course_files_alter_file_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
